import { font_tokens } from './font';

export const typography = {
  // Heading
  h1Bold: {
    fontFamily: font_tokens.bold,
    fontSize: 48,
    lineHeight: 72,
    letterSpacing: 0,
  },
  h1SemiBold: {
    fontFamily: font_tokens.semibold,
    fontSize: 48,
    lineHeight: 72,
    letterSpacing: 0,
  },
  h1Medium: {
    fontFamily: font_tokens.medium,
    fontSize: 48,
    lineHeight: 72,
    letterSpacing: 0,
  },
  h1Regular: {
    fontFamily: font_tokens.regular,
    fontSize: 48,
    lineHeight: 72,
    letterSpacing: 0,
  },
  h2Bold: {
    fontFamily: font_tokens.bold,
    fontSize: 40,
    lineHeight: 60,
    letterSpacing: 0,
  },
  h2SemiBold: {
    fontFamily: font_tokens.semibold,
    fontSize: 40,
    lineHeight: 60,
    letterSpacing: 0,
  },
  h2Medium: {
    fontFamily: font_tokens.medium,
    fontSize: 40,
    lineHeight: 60,
    letterSpacing: 0,
  },
  h2Regular: {
    fontFamily: font_tokens.regular,
    fontSize: 40,
    lineHeight: 60,
    letterSpacing: 0,
  },
  h3Bold: {
    fontFamily: font_tokens.bold,
    fontSize: 32,
    lineHeight: 48,
    letterSpacing: 0,
  },
  h3SemiBold: {
    fontFamily: font_tokens.semibold,
    fontSize: 32,
    lineHeight: 48,
    letterSpacing: 0,
  },
  h3Medium: {
    fontFamily: font_tokens.medium,
    fontSize: 32,
    lineHeight: 48,
    letterSpacing: 0,
  },
  h3Regular: {
    fontFamily: font_tokens.regular,
    fontSize: 32,
    lineHeight: 48,
    letterSpacing: 0,
  },
  h4Bold: {
    fontFamily: font_tokens.bold,
    fontSize: 24,
    lineHeight: 36,
    letterSpacing: 0,
  },
  h4SemiBold: {
    fontFamily: font_tokens.semibold,
    fontSize: 24,
    lineHeight: 36,
    letterSpacing: 0,
  },
  h4Medium: {
    fontFamily: font_tokens.medium,
    fontSize: 24,
    lineHeight: 36,
    letterSpacing: 0,
  },
  h4Regular: {
    fontFamily: font_tokens.regular,
    fontSize: 24,
    lineHeight: 36,
    letterSpacing: 0,
  },
  h5Bold: {
    fontFamily: font_tokens.bold,
    fontSize: 20,
    lineHeight: 30,
    letterSpacing: 0,
  },
  h5SemiBold: {
    fontFamily: font_tokens.semibold,
    fontSize: 20,
    lineHeight: 30,
    letterSpacing: 0,
  },
  h5Medium: {
    fontFamily: font_tokens.medium,
    fontSize: 20,
    lineHeight: 30,
    letterSpacing: 0,
  },
  h5Regular: {
    fontFamily: font_tokens.regular,
    fontSize: 20,
    lineHeight: 30,
    letterSpacing: 0,
  },
  h6Bold: {
    fontFamily: font_tokens.bold,
    fontSize: 18,
    lineHeight: 27,
    letterSpacing: 0,
  },
  h6SemiBold: {
    fontFamily: font_tokens.semibold,
    fontSize: 18,
    lineHeight: 27,
    letterSpacing: 0,
  },
  h6Medium: {
    fontFamily: font_tokens.medium,
    fontSize: 18,
    lineHeight: 27,
    letterSpacing: 0,
  },
  h6Regular: {
    fontFamily: font_tokens.regular,
    fontSize: 18,
    lineHeight: 27,
    letterSpacing: 0,
  },

  // Body
  bodyLgBold: {
    fontFamily: font_tokens.bold,
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0,
  },
  bodyLgSemiBold: {
    fontFamily: font_tokens.semibold,
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0,
  },
  bodyLgMedium: {
    fontFamily: font_tokens.medium,
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0,
  },
  bodyLgRegular: {
    fontFamily: font_tokens.regular,
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0,
  },
  bodyMdBold: {
    fontFamily: font_tokens.bold,
    fontSize: 14,
    lineHeight: 21,
    letterSpacing: 0,
  },
  bodyMdSemiBold: {
    fontFamily: font_tokens.semibold,
    fontSize: 14,
    lineHeight: 21,
    letterSpacing: 0,
  },
  bodyMdMedium: {
    fontFamily: font_tokens.medium,
    fontSize: 14,
    lineHeight: 21,
    letterSpacing: 0,
  },
  bodyMdRegular: {
    fontFamily: font_tokens.regular,
    fontSize: 14,
    lineHeight: 21,
    letterSpacing: 0,
  },
  bodySmBold: {
    fontFamily: font_tokens.bold,
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0,
  },
  bodySmSemiBold: {
    fontFamily: font_tokens.semibold,
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0,
  },
  bodySmMedium: {
    fontFamily: font_tokens.medium,
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0,
  },
  bodySmRegular: {
    fontFamily: font_tokens.regular,
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0,
  },
};
