export const icons = {
  google: require('./google.png'),
  apple: require('./apple.png'),
  facebook: require('./facebook.png'),
  check: require('./check.png'),
  inBetween: require('./in-between.png'),
  down: require('./arrow-down.png'),
  up: require('./arrow-up.png'),
  logo: require('./logo.png'),
  back: require('./back.png'),
  home: require('./home.png'),
  discover: require('./discover.png'),
  chat: require('./chat.png'),
  user: require('./user.png'),
};
